# Generated by Django 3.2.12 on 2022-04-17 12:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories01Accessories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('feature', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Accessories02Type',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Accessory Type',
            },
        ),
        migrations.CreateModel(
            name='Accessories03Brand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Brand Name')),
            ],
            options={
                'verbose_name': 'Accessory Brand',
            },
        ),
        migrations.CreateModel(
            name='Accessories05Price',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('type', models.SmallIntegerField(choices=[(1, 'Daraz'), (2, 'SastoDeal')], default=2)),
                ('discount_price', models.FloatField()),
                ('has_discount', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop01Laptop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('feature', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop02RAM',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='RAM')),
            ],
            options={
                'verbose_name': 'Laptop Ram',
            },
        ),
        migrations.CreateModel(
            name='Laptop03Brand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Brand Name')),
            ],
            options={
                'verbose_name': 'Laptop Brand',
            },
        ),
        migrations.CreateModel(
            name='Laptop04Storage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop05Processor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop06GPU',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('vRAM', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop07display',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop08OS',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop10Price',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('type', models.SmallIntegerField(choices=[(1, 'Daraz'), (2, 'SastoDeal')], default=2)),
                ('discount_price', models.FloatField()),
                ('has_discount', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews01Laptop_Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('raings', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.accessories01accessories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop09images',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img_url', models.ImageField(upload_to='')),
                ('accessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.laptop01laptop')),
            ],
        ),
        migrations.AddField(
            model_name='laptop01laptop',
            name='RAM',
            field=models.ManyToManyField(to='reviewer.Laptop02RAM'),
        ),
        migrations.AddField(
            model_name='laptop01laptop',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.laptop03brand'),
        ),
        migrations.AddField(
            model_name='laptop01laptop',
            name='display',
            field=models.ManyToManyField(to='reviewer.Laptop07display'),
        ),
        migrations.AddField(
            model_name='laptop01laptop',
            name='gpu',
            field=models.ManyToManyField(to='reviewer.Laptop06GPU'),
        ),
        migrations.AddField(
            model_name='laptop01laptop',
            name='os',
            field=models.ManyToManyField(to='reviewer.Laptop08OS'),
        ),
        migrations.AddField(
            model_name='laptop01laptop',
            name='prices',
            field=models.ManyToManyField(to='reviewer.Laptop10Price'),
        ),
        migrations.AddField(
            model_name='laptop01laptop',
            name='processor',
            field=models.ManyToManyField(to='reviewer.Laptop05Processor'),
        ),
        migrations.AddField(
            model_name='laptop01laptop',
            name='storage',
            field=models.ManyToManyField(to='reviewer.Laptop04Storage'),
        ),
        migrations.CreateModel(
            name='Bookmark02Accessories_Bookmark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.accessories01accessories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark01Laptop_Bookmark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.laptop01laptop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog01Blog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accessories04images',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img_url', models.ImageField(upload_to='')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.accessories01accessories')),
            ],
        ),
        migrations.AddField(
            model_name='accessories01accessories',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.accessories03brand'),
        ),
        migrations.AddField(
            model_name='accessories01accessories',
            name='prices',
            field=models.ManyToManyField(to='reviewer.Accessories05Price'),
        ),
        migrations.AddField(
            model_name='accessories01accessories',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.accessories02type'),
        ),
    ]
