# Generated by Django 3.2.12 on 2022-04-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories05price',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='laptop10price',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop10price',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
