# Generated by Django 3.2.12 on 2022-04-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20220417_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories05price',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='laptop10price',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
