# Generated by Django 3.2.12 on 2022-04-18 19:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviewer', '0005_user01qrcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews01Accessories_Review',
            new_name='Reviews02Accessories_Review',
        ),
    ]
