# Generated by Django 3.2.12 on 2022-04-18 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviewer', '0006_rename_reviews01accessories_review_reviews02accessories_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user01qrcode',
            name='grant_verfication',
        ),
        migrations.AddField(
            model_name='user01qrcode',
            name='img_url',
            field=models.ImageField(default=1, upload_to='images/qr'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='User02Verification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grant_verfication', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
