# Generated by Django 3.2.12 on 2022-04-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0007_auto_20220419_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessories01accessories',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='blog01blog',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='laptop01laptop',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='reviews01laptop_review',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='reviews02accessories_review',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='accessories01accessories',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog01blog',
            name='thumbnail',
            field=models.ImageField(upload_to='images/blogs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop01laptop',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
