# Generated by Django 3.2.12 on 2022-04-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0008_auto_20220421_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop10price',
            name='img_url',
        ),
    ]
