# Generated by Django 3.2.12 on 2022-04-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0009_remove_laptop10price_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop09images',
            old_name='accessories',
            new_name='laptop',
        ),
    ]
