from django.urls import path
from . import views
from django.urls.conf import include
urlpatterns = [
    path('', views.index, name="homepage"),
    path('scrap/', views.scrap, name="scrap"),
    path('sendmail/', views.send_mail, name="send mail"),
    path('blog/', views.blog, name="blog index"),
    path('blog/create/', views.blog_create, name="blog create"),
    path('blog/<int:id>/delete/', views.blog_delete, name="blog delete"),
    path('blog/<int:id>/edit/', views.blog_edit, name="blog edit"),
    path('blog/<int:id>/detail/', views.blog_detail, name="blog detail"),
    path('blog/<int:id>/userview/', views.blog_userview, name="blog user view"),
    path('bloglist/', views.blog_list, name="blog user index"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('register/', views.register, name="register"),
    path('laptop/', views.laptop, name="laptop index"),
    path('laptop/create/', views.laptop_create, name="laptop create"),
    path('laptop/<int:id>/delete/', views.laptop_delete, name="laptop delete"),
    path('laptop/<int:id>/edit/', views.laptop_edit, name="laptop edit"),
    path('laptop/<int:id>/detail/', views.laptop_detail, name="laptop detail"),
    path('laptop/<int:id>/userview/', views.laptop_view, name="laptop user view"),
    path('laptoplist/', views.laptop_list, name="laptop user index"),
    path('bookmarklaptop/<int:id>', views.bookmark_laptop, name="bookmark laptop"),
    path('bookmarkaccessory/<int:id>', views.bookmark_accessory, name="bookmark accessory"),
    path('accessory/', views.accessory, name="accessory index"),
    path('accessory/create', views.accessory_create, name="accessory create"),
    path('accessory/<int:id>/delete/', views.accessory_delete, name="accessory delete"),
    path('accessory/<int:id>/edit/', views.accessory_edit, name="accessory edit"),
    path('accessory/<int:id>/detail/', views.accessory_detail, name="accessory detail"),
    path('accessory/<int:id>/userview/', views.accessory_view, name="accessory user view"),
    path('accessorylist/', views.accessory_list, name="accessory user index"),
    path('search/', views.search_panel, name="search panel"),
    path('laptopreview/<int:id>', views.laptop_review, name="laptop review"),
    path('accessoryreview/<int:id>', views.accessory_review, name="accessory review"),
    path('compare/', views.compare, name="compare"),
    path('ajaxcompare/<int:id>', views.ajax_compare, name="ajax compare"),
    path('verify/', views.verify, name="verify"),
    path('verify_user/', views.verify_user, name="verify user"),    
    path('bookmarklist/', views.bookmark_list, name="bookmark list"),
    path('searchlaptop/', views.laptop_search_panel, name="search panel laptop"),
    path('confirmverification/<int:id>', views.confirm_verification, name="confirm verification"),
]